// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_1_start);
QT_DECLARE_EXTERN_RESOURCE(qmake_1_start);
QT_DECLARE_EXTERN_RESOURCE(_1_start_raw_qml_0);


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_1_start);

class 1_startPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    1_startPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_1_start);
QT_KEEP_RESOURCE(qmlcache_1_start);
QT_KEEP_RESOURCE(qmake_1_start);
QT_KEEP_RESOURCE(_1_start_raw_qml_0);
    }
};



#include "1_startplugin_1_startPlugin.moc"
